### ISSUE TITLE
test_negative_set_parameter sometimes fails to navigate to the entity

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/airgun#309] opened 2019-03-27 12:07 UTC
the test consists of 2 actions:
- domain create
- domain update

- however, the update step tries to click at the filtered result and then navigates to the "parameters" tab. But sometimes, the click is not really performed (or it's not properly registered by satellite) and thus it stays at the results screen.

The test then fails on accessing "parameters" tab, however, it should properly fail on the navigation already.
It looks like it does not perform any kind of `am_i_here` method.

**Comment by mirzal** [comment] 2019-06-28 16:02
@rplevka From your description, it seems this is fundamentally duplicate of #247 . The root cause is that `am_i_here` - perhaps surprisingly - runs only **before** navigation, as it is used to verify if we are on correct screen already. We do not use it to verify that navigation did succeed.

If you disagree and think this is different problem, feel free to re-open this issue.

**Closed by mirzal** 2019-06-28 16:02 UTC
