### ISSUE TITLE
Skip dashboard on UI tests

### ISSUE THREAD

**Issue by peterdragun** [SatelliteQE/airgun#406] opened 2019-10-08 09:14 UTC
In the present every UI test starts at dashboard after logging in. Loading dashboard is not necessary in most cases and takes some time. When you log in, dashboard is loaded, then you change organization and dashboard is loading again, then you change location and again loading. I feel this a bit annoying and time consuming.
Is there any way to skip loading dashboard? Maybe use URL to jump at page that test really use. For example tests for hosts will start at "example.com/hosts", then you are requested to login and after that you are at page you will really use.
There are some tests that already test dashboard so it will be covered even if we skip this page in most cases. I think this could reduce time needed for UI testing.

**Comment by mirekdlugosz** [comment] 2019-10-08 14:04
I'm assuming that you mean noticeable time that passes between starting to display dashboard (after logging in) and before interacting with menu.

However, this wait is not related to dashboard loading state. It's caused by Navmazing counter-intuitive behavior and the way we usually implement `is_displayed` for views.

Navmazing navigation works from destination backwards - you tell it where you want to be, and it first will check if it's already there. If not, it will call `prerequisite`, which usually tries to navigate to previous page, one from which we know how to navigate to destination.

Checking if you are already at destination is done by `am_i_here`, which usually defaults to implementation provided in [navigation.py](https://github.com/SatelliteQE/airgun/blob/master/airgun/navigation.py#L57) , which basically calls view's `is_displayed`. Most of the time, `is_displayed` calls `wait_for_element` ([example](https://github.com/SatelliteQE/airgun/blob/master/airgun/views/host.py#L213)), which will wait for up to 5 seconds before returning False (see [widgetastic browser](https://github.com/RedHatQE/widgetastic.core/blob/master/src/widgetastic/browser.py#L272)).

So, at the beginning of every page traversal, we want to determine if we need any navigation at all. But we wait before giving any sort of answer, since we don't know why element is not there - because we are on wrong place, or because page has not fully loaded yet.

**Comment by vijay8451** [comment] 2019-10-09 03:26
Just to add in same line .. to  jump directly at page also does not make much benefit  because it's (Navmazing) doing the real time navigation as similar to we do manual and then start destination navigation for actions.

**Comment by xdragu01** [comment] 2019-10-09 09:39
Thank you for clarification.
I just wanted to skip first navigation, not all of it (not sure if this is possible). There are tests that start on one page and then navigate to another. So bug mentioned in comment above will still be detected. I don't think we will lose any test coverage here. 
I still think that this could reduce some time, when you are already at page that you use. And also reduce number of `is_displayed` calling.
If I understand it correctly, when widgetastic have't found any element, it will try it again. This will take up to 10 seconds on every UI test. But when you are already at page you need this time will be reduced below 5 seconds in most cases. And this is not including time needed to navigate. It seems like few seconds won't make difference, but considering number of tests we have, this could save us a lot of time.

**Comment by mirekdlugosz** [comment] 2019-10-09 15:47
> If I understand it correctly, when widgetastic have't found any element, it will try it again. This will take up to 10 seconds on every UI test. But when you are already at page you need this time will be reduced below 5 seconds in most cases. 

That is correct. When we are already at requested page, we will get `True` immediately (or after couple of tries). But if we are on wrong page, we will wait for 5 seconds before getting `False` and proceeding with navigation. These 5 seconds is the buffer for case when we are on correct page, but it has not fully loaded yet.

> It seems like few seconds won't make difference, but considering number of tests we have, this could save us a lot of time.

Yes. We have ≈420 UI tests. 5 seconds for every single of them adds up to about 35 minutes per run that we waste doing nothing.

I believe this is reasonable speed optimization opportunity. We should try to tackle issue at its core - make `am_i_here` return `False` immediately if we can be certain we are on wrong page. Or rework navigation code so `am_i_here` is called on page that is fully-loaded. Or decouple `am_i_here` from `is_displayed`, as they are serving two distinct purposes.

Ideas, opinions and patches are most definitely welcome.

**Comment by mirekdlugosz** [comment] 2019-12-04 19:29
With #422 merged, most of tests will open "All entities" page instead of Dashboard upon login. Closing this ticket.

**Closed by mirekdlugosz** 2019-12-04 19:29 UTC
Labels: question
