### ISSUE TITLE
 self.browser.clear(self.search_field) doesn't work on foreman search boxes

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/airgun#249] opened 2018-11-27 15:08 UTC
The `clear` method has no effect on foreman search boxes. The method does not error out though, so the effect of repeated `session.<entity>.search("foo")` is that the search query is being chained.
Workaround for now is to manually aim at the "x" icon next to the search bar that clears the output, Or, the nastier way- navigating away from the page and re-visit it.

**Comment by abalakh** [comment] 2018-11-27 18:54
Couldn't reproduce for both katello and foreman entities. Tested on 6.5 SNAP4 and SNAP5.
My env: Chrome Version 70.0.3538.102, ChromeDriver 70.0.3538.97.
@rplevka @oshtaier What's your chrome(chromium) and, more importantly, chromedriver version?

**Comment by oshtaier** [comment] 2018-11-27 18:57
Just to be on the same page. Did you look exactly on a field with 'slash' on a beginning:
![image](https://user-images.githubusercontent.com/10895065/49104624-187aae00-f287-11e8-9d7a-149694be7ae7.png)

**Comment by abalakh** [comment] 2018-11-27 19:00
@oshtaier yep.
My findings:
Updating to Chrome Version 70.0.3538.110 (latest) didn't change a thing. BUT, after also updating chromedriver to latest - ChromeDriver 2.44.609545 (weird output in comparison to previous one btw) i was able to reproduce it. Seems like an issue in latest chromedriver itself (which doesn't surprise me, there was another regression in previous release).

**Comment by oshtaier** [comment] 2018-11-27 19:01
I didn't touch my environment for a while, so not sure about the details, but I can reproduce issue constantly

**Comment by abalakh** [comment] 2018-11-27 19:05
@oshtaier have you disabled chrome autoupdate? Chromedriver supports only few chrome versions, you should keep its version according to your Chrome version, otherwise issues like this may occur.
Ok, so i'm playing with both 
ChromeDriver 70.0.3538.97 (d035916fe243477005bc95fe2a5778b8f20b6ae1)
ChromeDriver 2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5)
and i can't reproduce it with 70.0.3538.97, but it's always reproducible on 2.44.609545, the issue is definitely there.

**Comment by oshtaier** [comment] 2018-11-27 19:05
okay, I will check the version tomorrow

**Comment by abalakh** [comment] 2018-11-27 19:23
Try this one tomorrow:
https://chromedriver.storage.googleapis.com/index.html?path=70.0.3538.97/

**Comment by vikask18** [comment] 2019-06-13 11:49
It looks like this issue still persists.

My findings so far:
- Navigation across pages clears the search box.
- While remaining on the same page and searching string multiple times appends the searched string one after other. The final result is that 
      - for negative assert tests this returns false positive - test passes.
      - for positive assert statements the test fails.

Also, I have tried updating the chrome driver to latest version - 75.0, but the issue remain persistent.

Anybody looking into this issue.

**Comment by vijay8451** [comment] 2019-06-13 11:56
@vikask18 under which test are you seeing this one ?

**Comment by vikask18** [comment] 2019-06-13 11:57
tests/foreman/ui/test_organization.py::test_positive_end_to_end

**Comment by vijay8451** [comment] 2019-06-13 13:02
as checked the tests issue more related to chrome browser/driver version latest version.
as works fine with firefox.

**Comment by vijay8451** [comment] 2019-06-13 13:21
@oshtaier any thought if you get any chance to see it ?

**Comment by oshtaier** [comment] 2019-06-13 14:12
hmm, it is huge chance that problem in chrome driver itself. If yes, so it is out of scope for my knowledge or my possibilities to fix

**Comment by rplevka** [comment] 2019-06-27 11:12
I have 2 scenarios running the same driver and versions, where 1 failed and the other passed:

failing: https://app.saucelabs.com/tests/eca5f253c29c4c958fe5f98c79db76b7
this one does not receive the CLEAR request and goes straight to another request:
```
10:29:71 POST moveto
10:29:93 SEND KEYS
```
passing: https://app.saucelabs.com/tests/805f961847f349478c6fd261fea4ba0f

the difference is, that the failing test misses the whole bunch of steps (check the passing tests requests since 09:46:98 - the first one is probably a `wait_for_ajax`

**Comment by vijay8451** [comment] 2019-09-03 07:23
I tried below way(a bit workaround to avoid wrong search):
```
session.browser.refresh()
```

**Comment by mirekdlugosz** [comment] 2019-12-13 16:08
Closing, as #344 and #383 got merged, and `tests/foreman/ui/test_organization.py::test_positive_end_to_end` passes just fine. I'm not sure there is any more work for us to do here.

If anyone disagrees, feel free to re-open and explain what still needs to be done.

**Closed by mirekdlugosz** 2019-12-13 16:08 UTC
Labels: Automation failure, critical
